<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.13">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Npgsql" Version="7.0.10" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Catalog.Domain\" />
    <None Remove="Controllers\" />
    <None Remove="Catalog.DAL\" />
    <None Remove="Catalog.DAL\Configuration\" />
    <None Remove="Catalog.DAL\Data\" />
    <None Remove="Catalog.DAL\Repositories\" />
    <None Remove="Catalog.DAL\Repositories\Interfaces\" />
    <None Remove="Catalog.DAL\UOW\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Catalog.Domain\" />
    <Folder Include="Controllers\" />
    <Folder Include="Catalog.DAL\" />
    <Folder Include="Catalog.DAL\Configuration\" />
    <Folder Include="Catalog.DAL\Data\" />
    <Folder Include="Catalog.DAL\Repositories\" />
    <Folder Include="Catalog.DAL\Repositories\Interfaces\" />
    <Folder Include="Catalog.DAL\UOW\" />
  </ItemGroup>
</Project>
