// <auto-generated />
using System;
using Catalog.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.DAL.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20251116005933_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("categories_pkey");

                    b.HasIndex("Name");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Rings"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Earrings"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Pendants"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Bracelets"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Necklaces"
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Metal", b =>
                {
                    b.Property<int>("MetalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("metalid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MetalId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("MetalId")
                        .HasName("metals_pkey");

                    b.HasIndex("Name");

                    b.ToTable("metals", (string)null);

                    b.HasData(
                        new
                        {
                            MetalId = 1,
                            Color = "Yellow",
                            Name = "Gold"
                        },
                        new
                        {
                            MetalId = 2,
                            Color = "White",
                            Name = "Gold"
                        },
                        new
                        {
                            MetalId = 3,
                            Color = "Rose",
                            Name = "Gold"
                        },
                        new
                        {
                            MetalId = 4,
                            Color = "Silver",
                            Name = "Silver"
                        },
                        new
                        {
                            MetalId = 5,
                            Color = "White",
                            Name = "Platinum"
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("manufacturer");

                    b.Property<int?>("MetalId")
                        .HasColumnType("integer")
                        .HasColumnName("metalid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<decimal?>("Size")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("size");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("weight");

                    b.HasKey("ProductId")
                        .HasName("products_pkey");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_product_category");

                    b.HasIndex("MetalId");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_product_name");

                    b.HasIndex("Price")
                        .HasDatabaseName("idx_product_price");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Manufacturer = "Ukraine",
                            MetalId = 2,
                            Name = "White Gold Ring with Diamond",
                            Price = 28000m,
                            Size = 16.5m,
                            Weight = 3.2m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Manufacturer = "Ukraine",
                            MetalId = 5,
                            Name = "Platinum Smoky Quartz Ring",
                            Price = 32000m,
                            Size = 16.5m,
                            Weight = 4.5m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Manufacturer = "Ukraine",
                            MetalId = 4,
                            Name = "Silver Amethyst Ring",
                            Price = 3100m,
                            Size = 17.5m,
                            Weight = 3.8m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Manufacturer = "Ukraine",
                            MetalId = 4,
                            Name = "Silver Ring with Cubic Zirconia",
                            Price = 1200m,
                            Size = 18m,
                            Weight = 8.5m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Manufacturer = "Ukraine",
                            MetalId = 2,
                            Name = "Diamond Stud Earrings",
                            Price = 28000m,
                            Weight = 2.1m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Manufacturer = "Ukraine",
                            MetalId = 2,
                            Name = "Emerald Earrings",
                            Price = 43000m,
                            Weight = 6.3m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2,
                            Manufacturer = "Ukraine",
                            MetalId = 4,
                            Name = "Silver Hoop Earrings with Cubic Zirconia",
                            Price = 3500m,
                            Weight = 4.2m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            Manufacturer = "Ukraine",
                            MetalId = 1,
                            Name = "Pearl Earrings",
                            Price = 12000m,
                            Weight = 3.5m
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3,
                            Manufacturer = "Ukraine",
                            MetalId = 4,
                            Name = "Cross Pendant with Onyx",
                            Price = 6600m,
                            Size = 2.5m,
                            Weight = 1.8m
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3,
                            Manufacturer = "Ukraine",
                            MetalId = 4,
                            Name = "Heart Pendant with Moonstone",
                            Price = 2150m,
                            Size = 2.0m,
                            Weight = 2.3m
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3,
                            Manufacturer = "Ukraine",
                            MetalId = 4,
                            Name = "Smoky Quartz Pendant",
                            Price = 9900m,
                            Size = 1.8m,
                            Weight = 1.5m
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3,
                            Manufacturer = "Ukraine",
                            MetalId = 4,
                            Name = "Garnet Pendant",
                            Price = 2000m,
                            Size = 1.5m,
                            Weight = 1.2m
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 4,
                            Manufacturer = "Ukraine",
                            MetalId = 4,
                            Name = "Silver Cross Bracelet with Onyx",
                            Price = 8900m,
                            Size = 19m,
                            Weight = 15.5m
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 4,
                            Manufacturer = "Ukraine",
                            MetalId = 4,
                            Name = "Moonstone and Opal Bracelet",
                            Price = 23000m,
                            Size = 18m,
                            Weight = 12.4m
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 4,
                            Manufacturer = "Ukraine",
                            MetalId = 5,
                            Name = "Thin Chain Bracelet",
                            Price = 5100m,
                            Size = 18m,
                            Weight = 3.1m
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4,
                            Manufacturer = "Ukraine",
                            MetalId = 2,
                            Name = "Pearl Bracelet",
                            Price = 26000m,
                            Size = 17.5m,
                            Weight = 9.8m
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 5,
                            Manufacturer = "Ukraine",
                            Name = "Pearl Necklace",
                            Price = 25000m,
                            Size = 45m,
                            Weight = 45.0m
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 5,
                            Manufacturer = "Ukraine",
                            MetalId = 4,
                            Name = "Garnet Necklace",
                            Price = 18500m,
                            Size = 50m,
                            Weight = 52.0m
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 5,
                            Manufacturer = "Ukraine",
                            MetalId = 4,
                            Name = "Diamond Necklace",
                            Price = 51500m,
                            Size = 48m,
                            Weight = 38.5m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Entities.ProductStone", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int>("StoneId")
                        .HasColumnType("integer")
                        .HasColumnName("stoneid");

                    b.HasKey("ProductId", "StoneId")
                        .HasName("product_stone_pkey");

                    b.HasIndex("StoneId");

                    b.ToTable("product_stone", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            StoneId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            StoneId = 11
                        },
                        new
                        {
                            ProductId = 3,
                            StoneId = 5
                        },
                        new
                        {
                            ProductId = 4,
                            StoneId = 9
                        },
                        new
                        {
                            ProductId = 5,
                            StoneId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            StoneId = 3
                        },
                        new
                        {
                            ProductId = 7,
                            StoneId = 9
                        },
                        new
                        {
                            ProductId = 8,
                            StoneId = 8
                        },
                        new
                        {
                            ProductId = 9,
                            StoneId = 10
                        },
                        new
                        {
                            ProductId = 10,
                            StoneId = 4
                        },
                        new
                        {
                            ProductId = 11,
                            StoneId = 11
                        },
                        new
                        {
                            ProductId = 12,
                            StoneId = 6
                        },
                        new
                        {
                            ProductId = 13,
                            StoneId = 10
                        },
                        new
                        {
                            ProductId = 14,
                            StoneId = 4
                        },
                        new
                        {
                            ProductId = 14,
                            StoneId = 7
                        },
                        new
                        {
                            ProductId = 16,
                            StoneId = 8
                        },
                        new
                        {
                            ProductId = 17,
                            StoneId = 8
                        },
                        new
                        {
                            ProductId = 18,
                            StoneId = 6
                        },
                        new
                        {
                            ProductId = 19,
                            StoneId = 1
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Stone", b =>
                {
                    b.Property<int>("StoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("stoneid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoneId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("StoneId")
                        .HasName("stones_pkey");

                    b.HasIndex("Name");

                    b.ToTable("stones", (string)null);

                    b.HasData(
                        new
                        {
                            StoneId = 1,
                            Name = "Diamond"
                        },
                        new
                        {
                            StoneId = 2,
                            Name = "Ruby"
                        },
                        new
                        {
                            StoneId = 3,
                            Name = "Emerald"
                        },
                        new
                        {
                            StoneId = 4,
                            Name = "Moonstone"
                        },
                        new
                        {
                            StoneId = 5,
                            Name = "Amethyst"
                        },
                        new
                        {
                            StoneId = 6,
                            Name = "Garnet"
                        },
                        new
                        {
                            StoneId = 7,
                            Name = "Opal"
                        },
                        new
                        {
                            StoneId = 8,
                            Name = "Pearl"
                        },
                        new
                        {
                            StoneId = 9,
                            Name = "Cubic Zirconia"
                        },
                        new
                        {
                            StoneId = 10,
                            Name = "Onyx"
                        },
                        new
                        {
                            StoneId = 11,
                            Name = "Smoky Quartz"
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Product", b =>
                {
                    b.HasOne("Catalog.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories");

                    b.HasOne("Catalog.Domain.Entities.Metal", "Metal")
                        .WithMany("Products")
                        .HasForeignKey("MetalId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_products_metals");

                    b.Navigation("Category");

                    b.Navigation("Metal");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.ProductStone", b =>
                {
                    b.HasOne("Catalog.Domain.Entities.Product", "Product")
                        .WithMany("ProductStones")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productstone_products");

                    b.HasOne("Catalog.Domain.Entities.Stone", "Stone")
                        .WithMany("ProductStones")
                        .HasForeignKey("StoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productstone_stones");

                    b.Navigation("Product");

                    b.Navigation("Stone");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Metal", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductStones");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Stone", b =>
                {
                    b.Navigation("ProductStones");
                });
#pragma warning restore 612, 618
        }
    }
}
