<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Entities\" />
    <None Remove="Common\" />
    <None Remove="Exceptions\" />
    <None Remove="ValueObjects\" />
    <None Remove="Interfaces\" />
    <None Remove="Interfaces\Services\" />
    <None Remove="Interfaces\Repositories\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Entities\" />
    <Folder Include="Common\" />
    <Folder Include="Exceptions\" />
    <Folder Include="ValueObjects\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Interfaces\Services\" />
    <Folder Include="Interfaces\Repositories\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MongoDB.Bson" Version="2.28.0" />
  </ItemGroup>
</Project>
