<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.0" />
        <PackageReference Include="FluentAssertions" Version="8.9.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\CatalogService\Catalog.BLL\Catalog.BLL.csproj" />
      <ProjectReference Include="..\..\CatalogService\Catalog.DAL\Catalog.DAL.csproj" />
      <ProjectReference Include="..\..\CatalogService\Catalog.Domain\Catalog.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Helpers\" />
    </ItemGroup>

</Project>
